# Generated by Django 5.2.1 on 2025-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='exit', max_length=100, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(default='2025', verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
