# Generated by Django 5.2.1 on 2025-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_country_film_genre_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Год выпуска'),
        ),
    ]
